from datapackage import Package

package = Package()
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Алматы.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Астана.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Атырауская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Восточно-Казахстанкая Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Жамбыльская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Жетысуская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Западно-Казахстанская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Карагандийская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Костанайская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Кызылординская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Мангийстауская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Павлодарская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Северо-Казахстанская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Туркестанская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Улытауская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Шымкент.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Абайская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Акмолинская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Актюбинская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\archive\Алматинская Область.XLSX")
package.infer(r"C:\Users\USER\Desktop\Практика\city-crime\data\comb.csv")
package.commit()
package.save( r"C:\Users\USER\Desktop\Практика\city-crime\datapackage.json")
